import './globals.css'
import { Inter } from '@next/font/google'
import Navbar from '../../src/app/components/Navbar'


const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Digital Smile',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png"/>
      </head>
      <body className={inter.className}>
        <Navbar />  
        {children}
      </body>
    </html>
  )
}
